# Generated by Django 5.2.13 on 2026-05-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boituvaplaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParadasOnibus',
            new_name='ParadaOnibus',
        ),
        migrations.RenameModel(
            old_name='Rotas',
            new_name='Rota',
        ),
    ]
