# Generated by Django 5.2.13 on 2026-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boituvaplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamarco',
            options={'verbose_name': 'Categoria de Marco', 'verbose_name_plural': 'Categorias de Marco'},
        ),
        migrations.AlterModelOptions(
            name='paradaonibus',
            options={'verbose_name': 'Parada de Ônibus', 'verbose_name_plural': 'Paradas de Ônibus'},
        ),
        migrations.AddField(
            model_name='local',
            name='tipo_local',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
