# Generated by Django 5.2.13 on 2026-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boituvaplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paradasonibus',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paradasonibus',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
